# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/3a-viz',
                'doc_host': 'https://arikru.github.io',
                'git_url': 'https://github.com/arikru/3a-viz',
                'lib_path': '3a_viz'},
  'syms': {'3a_viz.core': {'3a_viz.core.foo': ('core.html#foo', '3a_viz/core.py')}}}
